### ISSUE TITLE
Please create Cocoapod

### ISSUE THREAD

**Issue by alamodey** [shinjukunian/Mecab-Swift#3]
Hi, I'm unable to add this package through the Swift package manager:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/55496019/126031917-a8f320a9-aa1b-4c82-b0c7-5649f42e5289.png">

Would you be able to create a Cocoapod to simply the process? thanks.

**Comment by shinjukunian** [comment]
Hi,

thank you for reporting this. The latest commit on `master` 7734258 should have resolved this issue.
Please let me know if you run into any other problems.

Cheers from Tokyo

Morten
