### ISSUE TITLE
bool Param::open(const char *arg, const Option *opts) will cause memory leaks

### ISSUE THREAD

**Issue by CoderHJZhao** [shinjukunian/Mecab-Swift#9]
**fileName: param
methodName: bool Param::open(const char *arg, const Option *opts)**

The Xcode profile tool detects memory leaks in this method, which causes continuous memory growth and overheating of the phone. I hope you can optimize this issue when you have time. Thank you!
`char *string=ptr[2];
if (string!=NULL) {
    std::string str(string);
    size_t f=str.find("%20");
    
    while (f != std::string::npos) {
        str.replace(f, std::string("%20").length(), " ");
        f=str.find("%20");
    }
    
    char *file= new char[str.size()+1];
    sprintf(file, "%s",str.c_str());
    ptr[2]=file;
    
}
`

**Comment by shinjukunian** [comment]
#f0abf60 should address this
